Add project contributing guidelines
apcountryman/picolibrary pull request #392
Opened 2021-03-14 23:42 UTC by apcountryman

Resolves #3.

2021-03-18 01:07 UTC, apcountryman commented
Could you please give this a review @jaylamb ?

2021-03-18 04:02 UTC, jaylamb requested changes

2021-03-18 22:10 UTC, apcountryman commented
@jaylamb , GitHub seems to not be letting me "re-request review". Please give the updates a review when you have time.

2021-03-20 21:46 UTC, jaylamb approved these changes
Looks good!

2021-03-20 21:56 UTC, merged